---
- name: Clone TPV broker api repo
  ansible.builtin.git:
    repo: "{{ tpv_broker_repo }}"
    dest: "{{ tpv_broker_dir }}"
    version: "{{ tpv_broker_commit_id }}"
    force: "{{ tpv_broker_force_checkout | default(false) }}"

- name: Get TPV broker api current commit id
  ansible.builtin.command: git rev-parse HEAD
  args:
    chdir: "{{ tpv_broker_dir }}"
  register: tpv_broker_current_commit_id

- name: Add TPV broker api current commit id to a file
  ansible.builtin.copy:
    content: "Commit id: {{ tpv_broker_current_commit_id.stdout }}"
    dest: "{{ tpv_broker_dir }}/version"
    owner: root
    group: root
    mode: 0644

- name: Create a virtualenv and install dependencies
  ansible.builtin.pip:
    requirements: "{{ tpv_broker_dir }}/requirements.txt"
    virtualenv: "{{ tpv_broker_venv_dir }}"
    virtualenv_command: "{{ tpv_broker_virtualenv_command }}"
  environment:
    PYTHONPATH: null
    VIRTUAL_ENV: "{{ tpv_broker_venv_dir }}"
  become: true

- name: Copy TPV broker api systemd service file
  ansible.builtin.template:
    src: tpv_broker.service.j2
    dest: /etc/systemd/system/tpv_broker.service
    owner: root
    group: root
    mode: 0644
  register: tpv_broker_service

- name: Copy the cron job Script
  ansible.builtin.template:
    src: tpv_broker_cron.sh.j2
    dest: /usr/local/bin/tpv_broker_cron.sh
    owner: root
    group: root
    mode: 0755

- name: Create a cron job for the root user
  ansible.builtin.cron:
    name: "TPV broker api update cron job"
    minute: 5
    job: "/usr/local/bin/tpv_broker_cron.sh"
    user: root
    state: present

- name: Enable and start TPV broker api systemd service
  ansible.builtin.service:
    name: tpv_broker
    enabled: true
    state: started
    daemon_reload: true
  when: tpv_broker_service.changed

